### PR TITLE
Fix the labels

### PR DESCRIPTION
**Pull request by yangtcai**
only 
- [x] fix dataloader
link: #22 
fix labels

### CODE REVIEW

**Comment by yangtcai** [comment]
Hi, @williamstark01, I have fixed the problem with the labels, and there still have many none-repeatsequence-parts, should I change the generation stage?

**Comment by williamstark01** [comment]
> Hi, @williamstark01, I have fixed the problem with the labels, and there still have many none-repeatsequence-parts, should I change the generation stage?

What do you mean? Are there a lot of segments that don't contain repeats?

**Comment by yangtcai** [comment]
Hi, @williamstark01, I forget to change dtype, now I have fixed the errors, PTAL.
Currently, the total segments containing repeat sequence is only 8769. Compare with the whole number of segments 165970, the segments with repeat sequences occupy a little of the whole segments. I think there is a simple way to solve it, we can remove them when in the training stage. This solution will be very easy, but not fast.
The alternative solution is that we can change the generation datasets stage, when we generate the datasets, we can remove the redundancy of the segments without repeat sequences. I think this way may be fast than the first idea, because it only contains the segments with repeat sequences.
What do you think of it?

**Comment by williamstark01** [comment]
Looks good now!

Great to see you thought about the problem in detail. In general, it's not ideal to hardcode assumptions in the dataset generation stage, as it reduces the flexibility to testing different ideas later on. That increases the complexity of the item generation during training making it slower, as you say. Using workers for item batch generation though solves this problem, so we get the best of both options, making training fast again. (Workers generate the next batch in a separate process, so the main process running training, isn't affected at all.)

We can go even beyond that, and separate the repeat annotations `hg38.hits` file to one file per chromosome but do no other filtering in the dataset generation stage. Then, at the start of training use pandas to filter LTR, or other type of repeat types when the `Dataset` object is created, and select the segments with the appropriate repeat during training. Again, with worker processes training will still be fast.

Does that make sense?

All that said, if you strongly prefer to handle this in the dataset generation stage, go for it. For the first prototype, this is just a small implementation detail, not too important how we handle it.

**Review by williamstark01 — APPROVED** [review]
Great work, we got quite a turbo dataloader now :) And good to see you added the comment in the log, we might need it later on!

**Pull request merged**
